language: ruby

cache:
  bundler: true
  directories:
    - tmp/cache/assets/test/sprockets

rvm:
  - "2.3.1"

addons:
  postgresql: "9.5.4"

before_script:
 - sudo service postgresql start
 - cd JBB-Web/
 - gem install bundler
 - gem install rspec rspec-rails simplecov codeclimate-test-reporter
 - bundle install

script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec spec


notifications:
  email:
    recipients:
      - isaquealvesdl@gmail.com
